config/routes.rb
Libreria::Application.routes.draw do
  resources :editorials

  resources :authors

  resources :books

  get "sessions/new"
  get "users/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  root :to => "sessions#new"
  resources :users
  resources :sessions

end

app/models/author.rb
class Author < ActiveRecord::Base
	attr_accessible :idauthor, :name
	has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :idbook, :name, :idauthor, :ideditorial
  belongs_to :author
  belongs_to :editorial
end

app/models/editorial.rb
class Editorial < ActiveRecord::Base
	attr_accessible :ideditorial, :name
	has_many :books
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation
  attr_accessible :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 def not_authenticated
  redirect_to login_url, :alert => "First login to access this page."
 end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:idauthor, :name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to :action => 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:idbook, :name, :idauthor, :ideditorial)
    end
end

app/controllers/editorials_controller.rb
class EditorialsController < ApplicationController
  before_action :set_editorial, only: [:show, :edit, :update, :destroy]

  # GET /editorials
  # GET /editorials.json
  def index
    @editorials = Editorial.all
  end

  # GET /editorials/1
  # GET /editorials/1.json
  def show
  end

  # GET /editorials/new
  def new
    @editorial = Editorial.new
  end

  # GET /editorials/1/edit
  def edit
  end

  # POST /editorials
  # POST /editorials.json
  def create
    @editorial = Editorial.new(editorial_params)

    respond_to do |format|
      if @editorial.save
        format.html { redirect_to @editorial, notice: 'Editorial was successfully created.' }
        format.json { render action: 'show', status: :created, location: @editorial }
      else
        format.html { render action: 'new' }
        format.json { render json: @editorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editorials/1
  # PATCH/PUT /editorials/1.json
  def update
    respond_to do |format|
      if @editorial.update(editorial_params)
        format.html { redirect_to @editorial, notice: 'Editorial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @editorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editorials/1
  # DELETE /editorials/1.json
  def destroy
    @editorial.destroy
    respond_to do |format|
      format.html { redirect_to editorials_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_editorial
      @editorial = Editorial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def editorial_params
      params.require(:editorial).permit(:ideditorial, :name)
    end
end

app/controllers/home_controller.rb
before_filter :require_login, :only => :secret

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
  user = login(params[:email], params[:password], params[:remember_me])
  if user
    #redirect_back_or_to root_url, :notice => "Logged in!"
    redirect_to "/books"
  else
    flash.now.alert = "Email or password was invalid"
    render :new
  end
end

def destroy
  logout
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
  @user = User.new
end

def create
  @user = User.new(params[:user])
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render :new
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def userIsCoordinator
	return current_user.id ==2
 end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/editorials_helper.rb
module EditorialsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idauthor %><br>
    <%= f.number_field :idauthor %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Idauthor</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.idauthor %></td>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idauthor:</strong>
  <%= @author.idauthor %>
</p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idbook %><br>
    <%= f.number_field :idbook %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :idauthor %><br>
   <select name="book[author_id]">
    <% Author.all.each do |c| %>
    <option value="<%= c.id %>"><%= c.name %></option>
    <% end %>
   </select>    
  </div>
  <div class="field">
    <%= f.label :ideditorial %><br>
    <select name="book[editorial_id]">
    <% Editorial.all.each do |c| %>
    <option value="<%= c.id %>"><%= c.name %></option>
    <% end %>
   </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_form_new.htm.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :idbook %><br>
    <%= f.number_field :idbook %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
 </div>
 <div class="field">
 <%= f.label :idauthor %><br>
 <select name="book[idauthor]">
 <% Author.all.each do |s| %>
 <option value="<%= s.id %>"><%= s.name %></option>
 <% end %>
 </select>
 </div>
<div class="field">
 <%= f.label :schedule_id %><br>
 <select name="book[ideditorial]">
 <% Editorial.all.each do |s| %>
 <option value="<%= s.id %>"><%= s.name %></option>
 <% end %>
 </select>
 </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Modificar Libro</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @book %> |
<%= link_to 'Atras', books_path %>

app/views/books/index.html.erb
<h1>Lista de Libros</h1>

<table>
  <thead>
    <tr>
      <th>Idbook</th>
      <th>Nombre</th>
      <th>Autor</th>
      <th>Editorial</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.idbook %></td>
        <td><%= book.name %></td>
        <td><%= book.idauthor %></td>
        <td><%= book.ideditorial %></td>
	<td><%=  %> </td>
        <td><%= link_to 'Mostrar', book %></td>
		<% if userIsCoordinator %>
        <td><%= link_to 'Editar', edit_book_path(book) %></td>
	<td><%= link_to "Eliminar",book, method: :delete %> </td>
		<% end %>      
</tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Libro', new_book_path %>

app/views/books/new.html.erb
<h1>Agregar Libro</h1>

<%= render 'form_new' %>

<%= link_to 'Atras', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>IdLibro:</strong>
  <%= @book.idbook %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @book.author.name %>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @book.editorial.name %>
</p>

<% if userIsCoordinator %>
    <%= link_to 'Editar', edit_book_path(@book) %> |
<% end %>
<%= link_to 'Atras', books_path %>

app/views/editorials/_form.html.erb
<%= form_for(@editorial) do |f| %>
  <% if @editorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@editorial.errors.count, "error") %> prohibited this editorial from being saved:</h2>

      <ul>
      <% @editorial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ideditorial %><br>
    <%= f.number_field :ideditorial %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editorials/edit.html.erb
<h1>Modificar Editorial</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @editorial %> |
<%= link_to 'Atras', editorials_path %>

app/views/editorials/index.html.erb
<h1> Editoriales </h1>

<table>
  <thead>
    <tr>
      <th>IdEditorial </th>
      <th> Nombre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @editorials.each do |editorial| %>
      <tr>
        <td><%= editorial.ideditorial %></td>
        <td><%= editorial.name %></td>
	<td><%= %></td>
        <td><%= %></td>
        <td><%= link_to 'Mostrar', editorial %></td>
        <td><%= link_to 'Editar', edit_editorial_path(editorial) %></td>
        <td><%= link_to 'Eliminar', editorial, method: :delete, data: { confirm: 'Esta seguro que desea Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Editorial', new_editorial_path %>

app/views/editorials/new.html.erb
<h1>Agregar Editorial</h1>

<%= render 'form' %>

<%= link_to 'Atras', editorials_path %>

app/views/editorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id Editorial:</strong>
  <%= @editorial.ideditorial %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @editorial.name %>
</p>

<%= link_to 'Editar', edit_editorial_path(@editorial) %> |
<%= link_to 'Atras', editorials_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
<title>Formulario de Busqueda</title>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log out", logout_path %>

<% end %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>